### ISSUE TITLE
store-0.7.13 fails to build with GHC 8.10

### ISSUE THREAD

**Issue by sjakobi** [mgsloan/store#165]
```
src/Data/Store/TypeHash/Internal.hs:67:17: error:
    Data constructor not in scope:
      Code :: Q (TExp a0) -> Q (TExp TypeHash)
   |
67 |     liftTyped = Code . unsafeTExpCoerce . lift
   |                 ^^^^
cabal: Failed to build store-0.7.13.
```

**Comment by sjakobi** [comment]
Apparently `Code` was introduced in `template-haskell-2.17` / GHC-9.0: https://hackage.haskell.org/package/template-haskell-2.18.0.0/changelog

**Comment by sjakobi** [comment]
I have revised v0.7.13 to prevent building with t-h-2.16: https://hackage.haskell.org/package/store-0.7.13/revisions/

**Comment by sjakobi** [comment]
I see that this is fixed in v0.7.14. Thanks! :)

BTW, for updating the GHA config, I recommend using `haskell-ci regenerate` with a recentish version of `haskell-ci`, ideally `master`. The required changes to the config often are rather non-obvious.

**Comment by sjakobi** [comment]
If you have any questions about `haskell-ci`, feel free to ping me or use https://github.com/haskell-CI/haskell-ci/issues. The maintainers are pretty responsive in my experience.
