### ISSUE TITLE
`store` no longer compiles with new version `vector-0.13.2.0`.

### ISSUE THREAD

**Issue by alaendle** [mgsloan/store#179]
E.g. and many similar error messages appear:
```
/home/curators/work/unpack-dir/unpacked/store-0.7.18-6e9fb2c1c59a9f2fb62abd0016841417b57b9a3e045088d48d65cc740cb1eeb9/src/Data/Store/Internal.hs:824:2: error: [GHC-39999]
           • No instance for ‘Store a’ arising from a use of ‘peek’
             Possible fix:
               add (Store a) to the context of the instance declaration
           • In a stmt of a 'do' block: c0f0 <- peek
             In the expression:
               do c0f0 <- peek
                  return (Data.Vector.Unboxed.Base.V_DoNotUnboxLazy c0f0)
             In an equation for ‘peek’:
                 peek
                   = do c0f0 <- peek
                        return (Data.Vector.Unboxed.Base.V_DoNotUnboxLazy c0f0)
           |
       824 | $(deriveManyStoreUnboxVector)
           |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
I will disable this package on stackage for now.
(fyi @snoyberg).

**Comment by Bodigrim** [comment]
As a Hackage trustee I revised a few latest releases with `vector < 0.13.2.0`.

**Comment by Bodigrim** [comment]
Fixing this issue requires https://github.com/snoyberg/mono-traversable/issues/244 being resolved first.

**Comment by jcmartin** [comment]
@mgsloan I think we can close this issue now.

@Bodigrim and @alaendle It should be okay to add `store` into the nightly builds on stackage again.
