### ISSUE TITLE
Can't build with ghc-prim-0.70

### ISSUE THREAD

**Issue by mimi1vx** [mgsloan/store#156]
ghc-9.0.0-alpha1, ghc-prim-0.7.0

I'm not sure if is this bug in upcoming ghc.

```
[   51s] /usr/bin/ghc --make -fbuilding-cabal-package -O -static -dynamic-too -dynosuf dyn_o -dynhisuf dyn_hi -outputdir dist/build -odir dist/build -hidir dist/build -stubdir dist/build -i -idist/build -isrc -idist/build/autogen -idist/build/global-autogen -Idist/build/autogen -Idist/build/global-autogen -Idist/build -optP-include -optPdist/build/autogen/cabal_macros.h -this-unit-id store-core-0.4.4.3-JZuiCyGuDibLovuSima4aL -hide-all-packages -Wmissing-home-modules -no-user-package-db -package-db dist/package.conf.inplace -package-id base-4.15.0.0 -package-id bytestring-0.10.12.0 -package-id ghc-prim-0.7.0 -package-id primitive-0.7.1.0-AlufBwyqdSJKrbsk2BiHmJ -package-id text-1.2.4.0 -package-id transformers-0.5.6.2 -XHaskell2010 Data.Store.Core Paths_store_core -Wall -fwarn-tabs -fwarn-incomplete-uni-patterns -fwarn-incomplete-record-updates -O2
[   52s] [1 of 2] Compiling Data.Store.Core  ( src/Data/Store/Core.hs, dist/build/Data/Store/Core.o, dist/build/Data/Store/Core.dyn_o )
[   52s] 
[   52s] src/Data/Store/Core.hs:52:28: error:
[   52s]     Module ‘GHC.Prim’ does not export ‘unsafeCoerce#’
[   52s]    |
[   52s] 52 | import           GHC.Prim (unsafeCoerce#, RealWorld, ByteArray#, copyByteArrayToAddr#, copyAddrToByteArray#)
[   52s]    |                            ^^^^^^^^^^^^^
[   52s] error: Bad exit status from /var/tmp/rpm-tmp.TGVPoW (%build)
[   52s] 
```

**Comment by mgsloan** [comment]
Fixed in `store-core-0.4.4.4`.  Can't try building `store` with ghc-9 yet as many dependencies have not yet been updated.

**Comment by mimi1vx** [comment]
works like charm

**Comment by Bodigrim** [comment]
As a Hackage trustee I revised `store-core-0.4.3...0.4.4.3` with `ghc-prim < 0.7` constraint to make broken configurations explicitly unbuildable.
