### ISSUE TITLE
fails to build with ghc-9.10.1

### ISSUE THREAD

**Issue by juhp** [mgsloan/store#181]
Stackage Nightly:
```
       Building library for store-0.7.19...
       [1 of 9] Compiling Data.Store.Impl
       [2 of 9] Compiling Data.Store.TH.Internal
       [3 of 9] Compiling Data.Store.TH
       [4 of 9] Compiling Data.Store.Internal
       /home/curators/work/unpack-dir/unpacked/store-0.7.19-692c05736d3522a142bedfc3aac85abea5f6a41776d116604a46d46f8f297097/src/Dat
a/Store/Internal.hs:392:12: error: [GHC-39999]
           • Could not deduce ‘IsSequence (SCV.Vector a)’
               arising from a use of ‘sizeSequence’
             from the context: Store a
               bound by the instance declaration
               at src/Data/Store/Internal.hs:391:10-40
             There are instances for similar types:
               instance Storable a => IsSequence (SV.Vector a)
                 -- Defined in ‘Data.Sequences’
               instance UV.Unbox a => IsSequence (UV.Vector a)
                 -- Defined in ‘Data.Sequences’
               instance IsSequence (V.Vector a) -- Defined in ‘Data.Sequences’
           • In the expression: sizeSequence
             In an equation for ‘size’: size = sizeSequence
             In the instance declaration for ‘Store (SCV.Vector a)’
           |
       392 |     size = sizeSequence
           |            ^^^^^^^^^^^^
        
       /home/curators/work/unpack-dir/unpacked/store-0.7.19-692c05736d3522a142bedfc3aac85abea5f6a41776d116604a46d46f8f297097/src/Dat
a/Store/Internal.hs:393:12: error: [GHC-39999]
           • Could not deduce ‘IsSequence (SCV.Vector a)’
               arising from a use of ‘pokeSequence’
             from the context: Store a
               bound by the instance declaration
               at src/Data/Store/Internal.hs:391:10-40
             There are instances for similar types:
               instance Storable a => IsSequence (SV.Vector a)
                 -- Defined in ‘Data.Sequences’
               instance UV.Unbox a => IsSequence (UV.Vector a)
                 -- Defined in ‘Data.Sequences’
               instance IsSequence (V.Vector a) -- Defined in ‘Data.Sequences’
           • In the expression: pokeSequence
             In an equation for ‘poke’: poke = pokeSequence
             In the instance declaration for ‘Store (SCV.Vector a)’
           |
       393 |     poke = pokeSequence
           |            ^^^^^^^^^^^^
        
       [9 of 9] Compiling System.IO.ByteBuffer
```

**Comment by mgsloan** [comment]
This will be resolved once https://github.com/snoyberg/mono-traversable/pull/247 is on hackage in the form of `mono-traverable-1.0.21.0`.

**Comment by alaendle** [comment]
But now the test-suite didn't compile...
```
Building test suite 'store-test' for store-0.7.19...
[1 of 5] Compiling Data.Store.UntrustedSpec
[2 of 5] Compiling Data.StoreSpec.TH
[3 of 5] Compiling Data.StoreSpec
/home/andreas/stackage/stackage/tmp.rkP8/store-0.7.19/test/Data/StoreSpec.hs:186:2: error: [GHC-39999]
    • Could not deduce ‘Generic (UV.DoNotUnboxNormalForm a)’
        arising from a use of ‘Test.SmallCheck.Series.$dmseries’
      from the context: Serial m a
        bound by the instance declaration
        at test/Data/StoreSpec.hs:(186,2)-(188,26)
    • In the expression:
        Test.SmallCheck.Series.$dmseries @(m) @(UV.DoNotUnboxNormalForm a)
      In an equation for ‘series’:
          series       
            = Test.SmallCheck.Series.$dmseries
                @(m) @(UV.DoNotUnboxNormalForm a)
      In the instance declaration for
        ‘Serial m (UV.DoNotUnboxNormalForm a)’
    |                  
186 | $(do let ns = [ ''UV.DoNotUnboxLazy, ''UV.DoNotUnboxStrict, ''UV.DoNotUnboxNormalForm ]
    |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
                       
/home/andreas/stackage/stackage/tmp.rkP8/store-0.7.19/test/Data/StoreSpec.hs:186:2: error: [GHC-39999]
    • Could not deduce ‘Generic (UV.DoNotUnboxStrict a)’
        arising from a use of ‘Test.SmallCheck.Series.$dmseries’
      from the context: Serial m a
        bound by the instance declaration
        at test/Data/StoreSpec.hs:(186,2)-(188,26)
    • In the expression:
        Test.SmallCheck.Series.$dmseries @(m) @(UV.DoNotUnboxStrict a)
      In an equation for ‘series’:
          series       
            = Test.SmallCheck.Series.$dmseries @(m) @(UV.DoNotUnboxStrict a)
      In the instance declaration for ‘Serial m (UV.DoNotUnboxStrict a)’
    |                  
186 | $(do let ns = [ ''UV.DoNotUnboxLazy, ''UV.DoNotUnboxStrict, ''UV.DoNotUnboxNormalForm ]
    |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
                       
/home/andreas/stackage/stackage/tmp.rkP8/store-0.7.19/test/Data/StoreSpec.hs:186:2: error: [GHC-39999]
[4 of 5] Compiling System.IO.ByteBufferSpec
    • Could not deduce ‘Generic (UV.DoNotUnboxLazy a)’
        arising from a use of ‘Test.SmallCheck.Series.$dmseries’
      from the context: Serial m a
        bound by the instance declaration
        at test/Data/StoreSpec.hs:(186,2)-(188,26)
    • In the expression:
        Test.SmallCheck.Series.$dmseries @(m) @(UV.DoNotUnboxLazy a)
      In an equation for ‘series’:
          series       
            = Test.SmallCheck.Series.$dmseries @(m) @(UV.DoNotUnboxLazy a)
      In the instance declaration for ‘Serial m (UV.DoNotUnboxLazy a)’
    |                  
186 | $(do let ns = [ ''UV.DoNotUnboxLazy, ''UV.DoNotUnboxStrict, ''UV.DoNotUnboxNormalForm ]
    |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```

**Comment by mgsloan** [comment]
@alaendle Fixed the test in `store-0.7.20`

**Comment by alaendle** [comment]
Thanks! Re-enabled tests in stackage.
